version: '3'

tasks:
  cmake:
    aliases:
      - cmake
    desc: "CMake project"
    cmds:
      - mkdir -p build && cd build && cmake ..

  cmake_debug:
    aliases:
      - cmake_debug
    desc: "CMake project in Debug mode"
    cmds:
      - mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..

  make:
    aliases:
      - make
    desc: "Make project"
    cmds:
      - cd build && make

  clean:
    aliases:
      - clean
    desc: "Cleaning build directory"
    cmds:
      - rm -rf build/*

  build:
    aliases:
      - build
    desc: "Building project"
    cmds:
      - task clean
      - task cmake
      - task make

  build_debug:
    aliases:
      - build_debug
    desc: "Building project in Debug mode"
    cmds:
      - task clean
      - task cmake_debug
      - task make

  run:
    aliases:
      - run
    desc: "Running BladesAndMonsters"
    cmds:
      - task build
      - cd build/bin && ./BladesAndMonsters

  gdb:
    aliases:
      - gdb
    desc: "Run BladesAndMonsters in gdb for debugging"
    cmds:
      - task build_debug
      - cd build/bin && gdb -tui ./BladesAndMonsters

  rerun:
    aliases:
      - rerun
    desc: "Running BladesAndMonsters (no rebuild)"
    cmds:
      - cd build/bin && ./BladesAndMonsters

